### ISSUE TITLE
[test].status file missing?

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Codes/regression_testing#139]
Ok, I've tried to set this to up work with Quokka (see PR: https://github.com/quokka-astro/quokka/pull/647).

I get an error after the test runs, saying it's missing `Sedov.status`:
```
working on test: Sedov
   re-making clean...
   building...

configuring Sedov build...
   mkdir /home/bwibking/regression-tests/quokka/builddir
   cmake    -S /home/bwibking/regression-tests/quokka/ -B /home/bwibking/regression-tests/quokka/builddir -DAMReX_SPACEDIM=3

building Sedov...
   cmake --build /home/bwibking/regression-tests/quokka/builddir -j 8 --  test_hydro3d_blast
   Compilation time: 124.261 s
   run & test directory: /home/bwibking/regression-tests/quokka-CPU-tests/2024-06-12-003/Sedov/
   copying files to run directory...
   path to input file: tests/blast_32.in
   running the test...
   mpirun -n 16 ./Sedov.ex blast_32.in  plotfile_prefix=Sedov_plt  checkpoint_prefix=Sedov_chk  amr.checkpoint_files_output=0
   Execution time: 21.545 s
   archiving the output...

cleaning AMReX CMake directories...

cleaning quokka-CPU CMake directories...

creating new test report...
Traceback (most recent call last):
  File "/home/bwibking/quokka/extern/regression_testing/./regtest.py", line 1323, in <module>
    n = test_suite(sys.argv[1:])
  File "/home/bwibking/quokka/extern/regression_testing/./regtest.py", line 1249, in test_suite
    num_failed = report.report_this_test_run(suite, args.make_benchmarks, args.note,
  File "/home/bwibking/quokka/extern/regression_testing/test_report.py", line 954, in report_this_test_run
    with open(benchStatusFile) as bf:
FileNotFoundError: [Errno 2] No such file or directory: 'Sedov.status'
```

Is the code expected to produce this file? I don't see this file referenced anywhere except in `test_report.py` where it tries to open this file:
```
bwibking@avatargpu:~/quokka/extern/regression_testing> grep -nR benchStatusFile
test_report.py:950:            benchStatusFile = "%s.status" % (test.name)
test_report.py:954:            with open(benchStatusFile) as bf:
```

**Comment by BenWibking** [comment]
@zingale Do you have any suggestions on how to debug this?

**Comment by BenWibking** [comment]
Fixed by https://github.com/AMReX-Codes/regression_testing/pull/144.
